### ISSUE TITLE
TTY should be optional

### ISSUE THREAD

**Issue by mweiden** [chanzuckerberg/fogg#127]
# Need
* As a developer using `fogg` in CI/CD pipelines, I want to use `make check-plan` to check the state of my terraform deployment, so that I know my infrastructure is properly deployed before deploying apps on top of it.

* As a developer using `fogg` in CI/CD pipelines, I want TTY to be optional in `fogg` Makefiles, so that I can run `fogg` make commands on non-TTY devices.

## Example
Running `fogg` make commands in a Gitlab pipeline will result in: `the input device is not a TTY`

**Comment by ryanking** [comment]
@mweiden We can almost certainly make this work. Which commands caused that?

**Comment by mweiden** [comment]
Pretty much anything with the `-t` option after `docker run` will cause this issue.

**Comment by ryanking** [comment]
@mweiden this is released in 0.14.0
