### ISSUE TITLE
AWS-Vault Support

### ISSUE THREAD

**Issue by henryou007** [chanzuckerberg/fogg#143]
Currently to make fogg work with AWS vault I have to modify the generated Makefile. Specifically, I have to manually pass all the AWS related environment variables through `docker_base`. `fogg apply` also overwrites this change every time. It would be less painful if the `docker_base` stub could be automatically generated for AWS vault use case.

**Comment by henryou007** [comment]
0. Yes. Sorry for the confusion
1. We have multiple accounts. The plan is to have the state file stay in the same account as provider. 
2. Yes.

**Comment by henryou007** [comment]
Here is what I did for now:
1. Assume role with aws-vault
2. Add these env variables into docker_base in Makefile
```	-e AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
    -e AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
    -e AWS_SECURITY_TOKEN=$(AWS_SECURITY_TOKEN) \
    -e AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN) \
    -e AWS_VAULT=$(AWS_VAULT) \
    -e AWS_REGION=$(AWS_REGION) \```
3. Use `make check-plan`, etc.

**Comment by ryanking** [comment]
Thanks @henryou007, was going to ask for that.

What I don't understand is this– if you have resources in 1 AWS account and the state files (via terraform backend) in another account, then you need to authenticate two different ways?

Actually as I type that I realize that the role you are assume could be granted permissions to write to the bucket across the account boundaries. Is that what you all do?

**Comment by ryanking** [comment]
@henryou007 we recently made a change that allows you to use fogg without docker. This means that any environment variables you have will be available.

This *should* mean you can do `aws-vault ... make apply`. Upgrade to latest fogg, set `use_docker: false` in fogg.json and `fogg apply`.
