### ISSUE TITLE
Make apply should support -auto-approve

### ISSUE THREAD

**Issue by chauvm** [chanzuckerberg/fogg#154]
With terraform, we can do `terraform apply -auto-approve` to skip the confirmation step. Is there a workaround for make? I tried `yes 'yes' | make apply` but it didn't work.

**Comment by ryanking** [comment]
@chauvm we've avoided this i hope that people will actually read plans before letting them be applied. Not sure I'm ready to give that up. Maybe there's some use case I'm not thinking of?

**Comment by chauvm** [comment]
It would be useful for scripting. Right now we have a script for engineers to reset their dev databases by their own that uses `terraform apply -auto-approve`:
https://github.com/FB-PLP/terraform-infra-management/blob/master/scripts/terraform/stack.rb#L28

It is safe to apply because this is a 2-step process: https://github.com/FB-PLP/terraform-infra-management/blob/master/scripts/README.md.
- Step 1 first verifies that we have a clean plan, then changes a user's database snapshot date and generates a plan (checksum) and commits these changes.
- Step 2 runs terraform apply after verifying that the plan output matches the committed plan. This is when we need `make apply -auto-approve`.

**Comment by ryanking** [comment]
@chauvm ok that makes sense. Do you want to have a go at implementing? We could pair on it.

**Comment by chauvm** [comment]
Yes I'd love to pair on this! I'll book a meeting in RWC on Oct 2 since I'll be out for Grace Hopper next week. Feel free to suggest a different time. Thanks!
