### ISSUE TITLE
Default Variables for Modules

### ISSUE THREAD

**Issue by henryou007** [chanzuckerberg/fogg#163]
fogg generates a blob in main.tf in the respective env after I `fogg apply`. If I specify the `module_source` for that component, it is going to generate a parameter for each variable defined in the module. For example 

```
module "my-default-module " {
  source                 = "../../../modules/my-default-module"
  env                    = "${local.env}"
}
```

I have to define `local.env` in another file within this component. 

However, fogg still generates a parameter for me if one of the variable has a default value. I will have to either delete that line in main.tf (which is auto-generated) or redeclare that variable with the default value (It kind of defy the purpose of setting up the default).

**Comment by ryanking** [comment]
@henryou007 yeah this makes sense. We will think about how to make this better.

**Comment by alldoami** [comment]
Bumping this because it is still an issue that I ran into.
