### ISSUE TITLE
bug in fogg travis-ci impl

### ISSUE THREAD

**Issue by ryanking** [chanzuckerberg/fogg#223]
situation - trying to add travis ci config, but one of the accounts does not have an id set

$ fogg apply
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1844328]

goroutine 1 [running]:
github.com/chanzuckerberg/fogg/plan.(*Plan).buildTravisCI(0xc00000a3c0, 0xc000450900, 0x1d6e354, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/plan/travisci.go:36 +0x1d8
github.com/chanzuckerberg/fogg/plan.Eval(0xc000450900, 0xc00053f300, 0x1d6e354, 0x6, 0x0)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/plan/plan.go:127 +0x2d2
github.com/chanzuckerberg/fogg/apply.Apply(0x1db7c60, 0xc00053f3c0, 0xc000450900, 0x25c4b40, 0x0, 0xc000450900, 0x0)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/apply/apply.go:41 +0x58
github.com/chanzuckerberg/fogg/cmd.glob..func1(0x25b8e60, 0x25e1518, 0x0, 0x0, 0x0, 0x0)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/cmd/apply.go:56 +0x225
github.com/chanzuckerberg/fogg/vendor/github.com/spf13/cobra.(*Command).execute(0x25b8e60, 0x25e1518, 0x0, 0x0, 0x25b8e60, 0x25e1518)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/chanzuckerberg/fogg/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x25b9320, 0xc00031a100, 0x0, 0x0)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/chanzuckerberg/fogg/vendor/github.com/spf13/cobra.(*Command).Execute(...)
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/vendor/github.com/spf13/cobra/command.go:800
github.com/chanzuckerberg/fogg/cmd.Execute()
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/cmd/root.go:44 +0xf8
main.main()
 /home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/main.go:13 +0x5d

**Comment by edulop91** [comment]
`/home/elopez/workspace/go/src/github.com/chanzuckerberg/fogg/plan/travisci.go:36 +0x1d8` is suspicious
