### ISSUE TITLE
installing old versions of fogg via brew

### ISSUE THREAD

**Issue by amarjandu** [chanzuckerberg/fogg#359]
I needed to install an older version of fogg (0.28.4) and would like to do so using `brew install fogg@0.28.4` however brew is not able to locate a formula for this version. Is there a way to install a specific version of fogg using brew?

**Comment by amarjandu** [comment]
this was also resolved by downloading the applicable release from (releases)[https://github.com/chanzuckerberg/fogg/releases] then using `./fogg apply`

**Comment by ryanking** [comment]
@amarjandu Homebrew does not make this easy. The official advice seems to be https://docs.brew.sh/Tips-N'-Tricks#installing-previous-versions-of-formulae
